import type { Metadata } from "next";

import "./globals.css";
import { SWRProvider } from "@/lib/provider/swr-provider";
// import { ThemeProvider } from "@/components/theme-provider";
import { Roboto_Mono } from "next/font/google";

const roboto = Roboto_Mono({ subsets: ["latin"], variable: "--font-roboto" });
export const metadata: Metadata = {
  title: "luthfiahmdf",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SWRProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`${roboto.className}  antialiased`}>
          {children}
        </body>
      </html>
    </SWRProvider>
  );
}
